chatwoot:
  target: lakehouse
  outputs:
    lakehouse:
      type: trino
      method: none
      user: trino
      password:
      catalog: clickhouse
      schema: chatwoot
      host: trino-master
      port: 8080
      http_scheme: http
      threads: 2
